events {}

http {
	#limit_req_zone: defines a shared memory zone for rate limiting
	#$binary_remote_addr: uses the client IP address to track requests
	#zone=global_limit:10m : creates a zone named "global_limit" with 10MB memory
	#rate=5r/s: allow 5 requests per second per IP address
	limit_req_zone $binary_remote_addr zone=global_limit:10m rate=5r/s;
	limit_req_status 429;
	
	# Server 1: Custom response (port 8080)
	server {
		listen 8080;

		location / {
			limit_req zone=global_limit;
			
			# Return custom HTML response
			add_header Content-Type text/html;
			return 200 '<html><body><h1>Solved</h1></body></html>';
		}
	}

	# Server 2: Error response (port 8081)
	server {
		listen 8081;
		
		location / {
			limit_req zone=global_limit;
			
			# Return HTTP error
			return 500;
		}
	}

	# HTTPS Server (port 443)
	server {
		listen 443 ssl;
		server_name localhost;

		# Tell nginx where the certs are
		ssl_certificate /etc/nginx/nginx.crt;
		ssl_certificate_key /etc/nginx/nginx.key;

		location / {
			limit_req zone=global_limit;
			
			add_header Content-Type text/html;
			return 200 '<html><body><h1>Solved with HTTPS</h1></body></html>';
		}
	} 
}
